analyzer:
 strong-mode: true
 errors:
   unused_element: error
   unused_import: error
   unused_local_variable: error
   dead_code: error

   # Allow importing .template.dart files without an analyzer error.
   uri_has_not_been_generated: ignore
 plugins:
   angular:
     enabled: true