name: example.ang
version: 0.0.1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  angular: ^5.1.0
  angular_forms: ^2.1.0
  angular_components: ^0.11.0
  slickdart:
    path: ../../../
  bootstrap_sass: any
  http: any
  angular_router: ^2.0.0-a
dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0
  build_test: ^0.10.3
  angular_test: ^2.1.0
  sass_builder: ^2.1.0
#transformers:
#  - sass_builder:

#      outputExtension: .scss.css