name: slickdart
version: 0.0.1
author: CJKAO <kaopeter@gmail.com>
description: "basic grid component port from SlickGrid.
homepage: https://github.com/cjkao/slickdart
documentation: https://github.com/mleibman/SlickGrid
dependencies:
  browser: '>=0.8.1'
  unittest: '>=0.8.1'
