name: slickdart
version: 0.2.0-beta.2
authors:
  - CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
#  browser: ^0.10.0
  logging: '>=0.11.0 <2.0.0'
dev_dependencies:
  build_runner: ^0.7.9+2
  build_web_compilers: ^0.3.0
#  dnd: any
#  angular: 1.1.2+2
#  angular2: ^2.0.0
#  angular_ui: any
#  html5: ^0.1.7
  test: any
#  polymer: ^1.0.0-rc.19
#  polymer_elements: ^1.0.0-rc.10
#  web_components: ^0.12.5
#  throttle_debounce: "^0.1.2+1"
#  initialize: any
#  datepicker: any
#  pubviz: any
#transformers:

#
#dependency_overrides:
# polymer:
#  hosted:
#   name: polymer
#   url: "http://pub.dart-polymer.com"
#  version: "1.0.0-rc.19.unofficial.1"
# polymer_interop:
#  hosted:
#   name: polymer_interop
#   url: "http://pub.dart-polymer.com"
#  version: "1.0.0-rc.11.exp.20170724.0"

#transformers:
##- polymer:
##    entry_points: web/example/polymer/editor-sample.html
#- $dart2js:
#    csp: false
#    sourceMaps: true
#    checked: true
#    minify: false
#    commandLineOptions:
#    - --trust-type-annotations
#    - --trust-primitives
#web:
#  compiler:
#    debug: dartdevc