name: slickdart
version: 0.1.7+2
author: CJKAO <kaopeter@gmail.com>, tonosama-atlacatl
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  logging: '>=0.11.0 <2.0.0'

dev_dependencies:
#  polymer: any
#  dnd: any
  angular: 1.1.2+2
  angular_ui: any
  test: any
  web_components: any
#  dev_compiler: any
#  initialize: any
#  datepicker: any
#  pubviz: any
#transformers:
#- polymer:
#    entry_points: web/example/EditorSample.html
transformers:
- $dart2js:
    csp: false
    sourceMaps: true
    checked: false
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
#- angular
