name: slickdart
version: 0.0.2
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid
homepage: https://github.com/cjkao/slickdart
documentation: https://github.com/mleibman/SlickGrid
dependencies:
  browser: '>=0.8.5'
  unittest: '>=0.8.5'
  html5_dnd: any
dev_dependencies:
  polymer: '>=0.8.5'