name: slickdart
version: 0.1.2+1
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
environment:
  sdk: '>=1.4.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  logging: '>=0.9.0 <0.12.0'

dev_dependencies:
#  polymer: any
#  dnd: any
  angular: any
  angular_ui: any
  unittest: any
#  web_components: any
#  initialize: any
#  datepicker: any
#  pubviz: any
#transformers:
#- polymer:
#    entry_points: web/example/EditorSample.html
#transformers:
#- angular
