name: slickdart
version: 0.1.1+4
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
dependencies:
  browser: any
  logging: any

dev_dependencies:
  polymer: any
  dnd: any
  unittest: any
  web_components: any
  initialize: any
  datepicker: any
#  pubviz: any
#transformers:
#- polymer