name: slickdart
version: 0.0.3
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid
homepage: https://github.com/cjkao/slickdart
documentation: https://github.com/mleibman/SlickGrid
dependencies:
  browser: '>=0.9.1 <0.9.2'
dev_dependencies:
  polymer: any
  unittest: any
  html5_dnd: any