name: slickdart
version: "0.1.0+1"
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
dependencies:
  browser: any
dev_dependencies:
  unittest: any
  dnd: any
  web_components: any
