name: slickdart
version: 0.0.4
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid
homepage: https://cjkao.github.io/slickdart
documentation: https://github.io/mleibman/SlickGrid
dependencies:
  browser: any
dev_dependencies:
  polymer: any
  unittest: any
  html5_dnd: any