name: slickdart
version: "0.1.0"
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
dependencies:
  browser: any
dev_dependencies:
  unittest: any
  html5_dnd: any
  web_components: any  #angular: '1.0.0'
  #di: any

#transformers:
#- angular