name: slickdart
version: "0.0.5+4"
author: CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
dependencies:
  browser: any
dev_dependencies:
  polymer: any
  unittest: any
  html5_dnd: any
  angular: any
  csvparser: any
