name: slickdart
version: 0.2.0+4
authors:
  - CJKAO <kaopeter@gmail.com>
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: '>=0.11.0 <2.0.0'
dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.4.0
  test: ^1.6.0

