name: slickdart
version: 0.1.8+3
authors:
  - CJKAO <kaopeter@gmail.com>
  - tonosama-atlacatl
  - yyyangd
description: Basic grid component port from SlickGrid with dynamic row height, frozen column enhancement
homepage: https://cjkao.github.io/slickdart
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  logging: '>=0.11.0 <2.0.0'

dev_dependencies:
#  dnd: any
#  angular: 1.1.2+2
#  angular_ui: any
  test: any
  polymer: ^1.0.0-rc.17
  polymer_elements: ^1.0.0-rc.8
  web_components: ^0.12.0
#  dev_compiler: any
#  initialize: any
#  datepicker: any
#  pubviz: any
#transformers:
#- polymer:
#    entry_points: web/example/EditorSample.html
transformers:
- polymer:
    entry_points:
      - web/example/polymer/editor-sample.html
- $dart2js:
    csp: false
    sourceMaps: true
    checked: false
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
